# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: utils/pb/suggestions/suggestions.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'utils/pb/suggestions/suggestions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&utils/pb/suggestions/suggestions.proto\x12\x14utils.pb.suggestions\">\n\x12SuggestionsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x17\n\x0fnum_suggestions\x18\x02 \x01(\x05\"$\n\x13SuggestionsResponse\x12\r\n\x05\x62ooks\x18\x01 \x03(\t\">\n\x0c\x45ventRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\r\n\x05\x65vent\x18\x02 \x01(\t\x12\r\n\x05\x63lock\x18\x03 \x01(\t\"@\n\rEventResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05\x63lock\x18\x03 \x01(\t\"5\n\x0c\x43learRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x13\n\x0b\x66inal_clock\x18\x02 \x01(\t\"@\n\rClearResponse\x12\x0f\n\x07\x63leared\x18\x01 \x01(\x08\x12\x0f\n\x07service\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t2\xa4\x02\n\x0bSuggestions\x12i\n\x12GetBookSuggestions\x12(.utils.pb.suggestions.SuggestionsRequest\x1a).utils.pb.suggestions.SuggestionsResponse\x12S\n\x08RunEvent\x12\".utils.pb.suggestions.EventRequest\x1a#.utils.pb.suggestions.EventResponse\x12U\n\nClearOrder\x12\".utils.pb.suggestions.ClearRequest\x1a#.utils.pb.suggestions.ClearResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.suggestions.suggestions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUGGESTIONSREQUEST']._serialized_start=64
  _globals['_SUGGESTIONSREQUEST']._serialized_end=126
  _globals['_SUGGESTIONSRESPONSE']._serialized_start=128
  _globals['_SUGGESTIONSRESPONSE']._serialized_end=164
  _globals['_EVENTREQUEST']._serialized_start=166
  _globals['_EVENTREQUEST']._serialized_end=228
  _globals['_EVENTRESPONSE']._serialized_start=230
  _globals['_EVENTRESPONSE']._serialized_end=294
  _globals['_CLEARREQUEST']._serialized_start=296
  _globals['_CLEARREQUEST']._serialized_end=349
  _globals['_CLEARRESPONSE']._serialized_start=351
  _globals['_CLEARRESPONSE']._serialized_end=415
  _globals['_SUGGESTIONS']._serialized_start=418
  _globals['_SUGGESTIONS']._serialized_end=710
# @@protoc_insertion_point(module_scope)
