# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: books_database.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'books_database.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x62ooks_database.proto\x12\x0e\x62ooks_database\"\x1c\n\x0bReadRequest\x12\r\n\x05title\x18\x01 \x01(\t\"?\n\x0cReadResponse\x12\r\n\x05stock\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"0\n\x0cWriteRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tnew_stock\x18\x02 \x01(\x05\"1\n\rWriteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"G\n\x10SyncWriteRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tnew_stock\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"5\n\x11SyncWriteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x0f\n\rStatusRequest\"\"\n\x0eStatusResponse\x12\x10\n\x08is_alive\x18\x01 \x01(\x08\x32\x98\x01\n\rBooksDatabase\x12\x41\n\x04Read\x12\x1b.books_database.ReadRequest\x1a\x1c.books_database.ReadResponse\x12\x44\n\x05Write\x12\x1c.books_database.WriteRequest\x1a\x1d.books_database.WriteResponse2\xab\x01\n\x0bReplicaSync\x12P\n\tSyncWrite\x12 .books_database.SyncWriteRequest\x1a!.books_database.SyncWriteResponse\x12J\n\tGetStatus\x12\x1d.books_database.StatusRequest\x1a\x1e.books_database.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'books_database_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_READREQUEST']._serialized_start=40
  _globals['_READREQUEST']._serialized_end=68
  _globals['_READRESPONSE']._serialized_start=70
  _globals['_READRESPONSE']._serialized_end=133
  _globals['_WRITEREQUEST']._serialized_start=135
  _globals['_WRITEREQUEST']._serialized_end=183
  _globals['_WRITERESPONSE']._serialized_start=185
  _globals['_WRITERESPONSE']._serialized_end=234
  _globals['_SYNCWRITEREQUEST']._serialized_start=236
  _globals['_SYNCWRITEREQUEST']._serialized_end=307
  _globals['_SYNCWRITERESPONSE']._serialized_start=309
  _globals['_SYNCWRITERESPONSE']._serialized_end=362
  _globals['_STATUSREQUEST']._serialized_start=364
  _globals['_STATUSREQUEST']._serialized_end=379
  _globals['_STATUSRESPONSE']._serialized_start=381
  _globals['_STATUSRESPONSE']._serialized_end=415
  _globals['_BOOKSDATABASE']._serialized_start=418
  _globals['_BOOKSDATABASE']._serialized_end=570
  _globals['_REPLICASYNC']._serialized_start=573
  _globals['_REPLICASYNC']._serialized_end=744
# @@protoc_insertion_point(module_scope)
