syntax = "proto3";
package utils.pb.books_database;

service BooksDatabase {
  // client‐visible operations
  rpc Read   (ReadRequest)  returns (ReadResponse);
  rpc Write  (WriteRequest) returns (WriteResponse);

  // internal replication
  rpc Replicate (ReplicateRequest) returns (ReplicateAck);
}

message ReadRequest {
  string title = 1;
}

message ReadResponse {
  int32 stock = 1;
}

message WriteRequest {
  string title     = 1;
  int32  new_stock = 2;
}

message WriteResponse {
  bool success = 1;
}

message ReplicateRequest {
  string title     = 1;
  int32  new_stock = 2;
  string clock     = 3; // JSON‐encoded vector clock
}

message ReplicateAck {
  bool success = 1;
}
