# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: utils/pb/books_database/books_database.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'utils/pb/books_database/books_database.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,utils/pb/books_database/books_database.proto\x12\x17utils.pb.books_database\"\x1c\n\x0bReadRequest\x12\r\n\x05title\x18\x01 \x01(\t\"\x1d\n\x0cReadResponse\x12\r\n\x05stock\x18\x01 \x01(\x05\"0\n\x0cWriteRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tnew_stock\x18\x02 \x01(\x05\" \n\rWriteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"D\n\x0ePrepareRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x11\n\tnew_stock\x18\x03 \x01(\x05\" \n\x0fPrepareResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\"0\n\rCommitRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\"!\n\x0e\x43ommitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\" \n\x0c\x41\x62ortRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\" \n\rAbortResponse\x12\x0f\n\x07\x61\x62orted\x18\x01 \x01(\x08\x32\xcd\x03\n\rBooksDatabase\x12S\n\x04Read\x12$.utils.pb.books_database.ReadRequest\x1a%.utils.pb.books_database.ReadResponse\x12V\n\x05Write\x12%.utils.pb.books_database.WriteRequest\x1a&.utils.pb.books_database.WriteResponse\x12\\\n\x07Prepare\x12\'.utils.pb.books_database.PrepareRequest\x1a(.utils.pb.books_database.PrepareResponse\x12Y\n\x06\x43ommit\x12&.utils.pb.books_database.CommitRequest\x1a\'.utils.pb.books_database.CommitResponse\x12V\n\x05\x41\x62ort\x12%.utils.pb.books_database.AbortRequest\x1a&.utils.pb.books_database.AbortResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.books_database.books_database_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_READREQUEST']._serialized_start=73
  _globals['_READREQUEST']._serialized_end=101
  _globals['_READRESPONSE']._serialized_start=103
  _globals['_READRESPONSE']._serialized_end=132
  _globals['_WRITEREQUEST']._serialized_start=134
  _globals['_WRITEREQUEST']._serialized_end=182
  _globals['_WRITERESPONSE']._serialized_start=184
  _globals['_WRITERESPONSE']._serialized_end=216
  _globals['_PREPAREREQUEST']._serialized_start=218
  _globals['_PREPAREREQUEST']._serialized_end=286
  _globals['_PREPARERESPONSE']._serialized_start=288
  _globals['_PREPARERESPONSE']._serialized_end=320
  _globals['_COMMITREQUEST']._serialized_start=322
  _globals['_COMMITREQUEST']._serialized_end=370
  _globals['_COMMITRESPONSE']._serialized_start=372
  _globals['_COMMITRESPONSE']._serialized_end=405
  _globals['_ABORTREQUEST']._serialized_start=407
  _globals['_ABORTREQUEST']._serialized_end=439
  _globals['_ABORTRESPONSE']._serialized_start=441
  _globals['_ABORTRESPONSE']._serialized_end=473
  _globals['_BOOKSDATABASE']._serialized_start=476
  _globals['_BOOKSDATABASE']._serialized_end=937
# @@protoc_insertion_point(module_scope)
