# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from utils.pb.books_database import books_database_pb2 as utils_dot_pb_dot_books__database_dot_books__database__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in utils/pb/books_database/books_database_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BooksDatabaseStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Read = channel.unary_unary(
                '/utils.pb.books_database.BooksDatabase/Read',
                request_serializer=utils_dot_pb_dot_books__database_dot_books__database__pb2.ReadRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_books__database_dot_books__database__pb2.ReadResponse.FromString,
                _registered_method=True)
        self.Write = channel.unary_unary(
                '/utils.pb.books_database.BooksDatabase/Write',
                request_serializer=utils_dot_pb_dot_books__database_dot_books__database__pb2.WriteRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_books__database_dot_books__database__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.Replicate = channel.unary_unary(
                '/utils.pb.books_database.BooksDatabase/Replicate',
                request_serializer=utils_dot_pb_dot_books__database_dot_books__database__pb2.ReplicateRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_books__database_dot_books__database__pb2.ReplicateAck.FromString,
                _registered_method=True)
        self.Prepare = channel.unary_unary(
                '/utils.pb.books_database.BooksDatabase/Prepare',
                request_serializer=utils_dot_pb_dot_books__database_dot_books__database__pb2.PrepareRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_books__database_dot_books__database__pb2.PrepareResponse.FromString,
                _registered_method=True)
        self.Commit = channel.unary_unary(
                '/utils.pb.books_database.BooksDatabase/Commit',
                request_serializer=utils_dot_pb_dot_books__database_dot_books__database__pb2.CommitRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_books__database_dot_books__database__pb2.CommitResponse.FromString,
                _registered_method=True)
        self.Abort = channel.unary_unary(
                '/utils.pb.books_database.BooksDatabase/Abort',
                request_serializer=utils_dot_pb_dot_books__database_dot_books__database__pb2.AbortRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_books__database_dot_books__database__pb2.AbortResponse.FromString,
                _registered_method=True)
        self.DecrementStock = channel.unary_unary(
                '/utils.pb.books_database.BooksDatabase/DecrementStock',
                request_serializer=utils_dot_pb_dot_books__database_dot_books__database__pb2.DecrementRequest.SerializeToString,
                response_deserializer=utils_dot_pb_dot_books__database_dot_books__database__pb2.DecrementResponse.FromString,
                _registered_method=True)


class BooksDatabaseServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Replicate(self, request, context):
        """-- replication RPC for primary → backups --
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Prepare(self, request, context):
        """2PC participant RPCs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Commit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Abort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecrementStock(self, request, context):
        """--- new atomic decrement RPC ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BooksDatabaseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=utils_dot_pb_dot_books__database_dot_books__database__pb2.ReadRequest.FromString,
                    response_serializer=utils_dot_pb_dot_books__database_dot_books__database__pb2.ReadResponse.SerializeToString,
            ),
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=utils_dot_pb_dot_books__database_dot_books__database__pb2.WriteRequest.FromString,
                    response_serializer=utils_dot_pb_dot_books__database_dot_books__database__pb2.WriteResponse.SerializeToString,
            ),
            'Replicate': grpc.unary_unary_rpc_method_handler(
                    servicer.Replicate,
                    request_deserializer=utils_dot_pb_dot_books__database_dot_books__database__pb2.ReplicateRequest.FromString,
                    response_serializer=utils_dot_pb_dot_books__database_dot_books__database__pb2.ReplicateAck.SerializeToString,
            ),
            'Prepare': grpc.unary_unary_rpc_method_handler(
                    servicer.Prepare,
                    request_deserializer=utils_dot_pb_dot_books__database_dot_books__database__pb2.PrepareRequest.FromString,
                    response_serializer=utils_dot_pb_dot_books__database_dot_books__database__pb2.PrepareResponse.SerializeToString,
            ),
            'Commit': grpc.unary_unary_rpc_method_handler(
                    servicer.Commit,
                    request_deserializer=utils_dot_pb_dot_books__database_dot_books__database__pb2.CommitRequest.FromString,
                    response_serializer=utils_dot_pb_dot_books__database_dot_books__database__pb2.CommitResponse.SerializeToString,
            ),
            'Abort': grpc.unary_unary_rpc_method_handler(
                    servicer.Abort,
                    request_deserializer=utils_dot_pb_dot_books__database_dot_books__database__pb2.AbortRequest.FromString,
                    response_serializer=utils_dot_pb_dot_books__database_dot_books__database__pb2.AbortResponse.SerializeToString,
            ),
            'DecrementStock': grpc.unary_unary_rpc_method_handler(
                    servicer.DecrementStock,
                    request_deserializer=utils_dot_pb_dot_books__database_dot_books__database__pb2.DecrementRequest.FromString,
                    response_serializer=utils_dot_pb_dot_books__database_dot_books__database__pb2.DecrementResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'utils.pb.books_database.BooksDatabase', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('utils.pb.books_database.BooksDatabase', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BooksDatabase(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/utils.pb.books_database.BooksDatabase/Read',
            utils_dot_pb_dot_books__database_dot_books__database__pb2.ReadRequest.SerializeToString,
            utils_dot_pb_dot_books__database_dot_books__database__pb2.ReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/utils.pb.books_database.BooksDatabase/Write',
            utils_dot_pb_dot_books__database_dot_books__database__pb2.WriteRequest.SerializeToString,
            utils_dot_pb_dot_books__database_dot_books__database__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Replicate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/utils.pb.books_database.BooksDatabase/Replicate',
            utils_dot_pb_dot_books__database_dot_books__database__pb2.ReplicateRequest.SerializeToString,
            utils_dot_pb_dot_books__database_dot_books__database__pb2.ReplicateAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Prepare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/utils.pb.books_database.BooksDatabase/Prepare',
            utils_dot_pb_dot_books__database_dot_books__database__pb2.PrepareRequest.SerializeToString,
            utils_dot_pb_dot_books__database_dot_books__database__pb2.PrepareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Commit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/utils.pb.books_database.BooksDatabase/Commit',
            utils_dot_pb_dot_books__database_dot_books__database__pb2.CommitRequest.SerializeToString,
            utils_dot_pb_dot_books__database_dot_books__database__pb2.CommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Abort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/utils.pb.books_database.BooksDatabase/Abort',
            utils_dot_pb_dot_books__database_dot_books__database__pb2.AbortRequest.SerializeToString,
            utils_dot_pb_dot_books__database_dot_books__database__pb2.AbortResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecrementStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/utils.pb.books_database.BooksDatabase/DecrementStock',
            utils_dot_pb_dot_books__database_dot_books__database__pb2.DecrementRequest.SerializeToString,
            utils_dot_pb_dot_books__database_dot_books__database__pb2.DecrementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
