# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: utils/pb/order_queue/order_queue.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'utils/pb/order_queue/order_queue.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&utils/pb/order_queue/order_queue.proto\x12\x14utils.pb.order_queue\"`\n\x0cOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x11\n\tnum_items\x18\x02 \x01(\x05\x12\x12\n\nis_premium\x18\x03 \x01(\x08\x12\x17\n\x0fshipping_method\x18\x04 \x01(\t\",\n\x08QueueAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"4\n\rOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x11\n\thas_order\x18\x02 \x01(\x08\x32\xa8\x01\n\nOrderQueue\x12M\n\x07\x45nqueue\x12\".utils.pb.order_queue.OrderRequest\x1a\x1e.utils.pb.order_queue.QueueAck\x12K\n\x07\x44\x65queue\x12\x1b.utils.pb.order_queue.Empty\x1a#.utils.pb.order_queue.OrderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.order_queue.order_queue_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERREQUEST']._serialized_start=64
  _globals['_ORDERREQUEST']._serialized_end=160
  _globals['_QUEUEACK']._serialized_start=162
  _globals['_QUEUEACK']._serialized_end=206
  _globals['_EMPTY']._serialized_start=208
  _globals['_EMPTY']._serialized_end=215
  _globals['_ORDERRESPONSE']._serialized_start=217
  _globals['_ORDERRESPONSE']._serialized_end=269
  _globals['_ORDERQUEUE']._serialized_start=272
  _globals['_ORDERQUEUE']._serialized_end=440
# @@protoc_insertion_point(module_scope)
