# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from transaction_verification import transaction_verification_pb2 as transaction__verification_dot_transaction__verification__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in transaction_verification/transaction_verification_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TransactionVerificationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CacheOrder = channel.unary_unary(
                '/transaction_verification.TransactionVerification/CacheOrder',
                request_serializer=transaction__verification_dot_transaction__verification__pb2.CachedOrderRequest.SerializeToString,
                response_deserializer=transaction__verification_dot_transaction__verification__pb2.CacheAck.FromString,
                _registered_method=True)
        self.ProcessOrder = channel.unary_unary(
                '/transaction_verification.TransactionVerification/ProcessOrder',
                request_serializer=transaction__verification_dot_transaction__verification__pb2.OrderProcessRequest.SerializeToString,
                response_deserializer=transaction__verification_dot_transaction__verification__pb2.TransactionVerificationResponse.FromString,
                _registered_method=True)
        self.RunEvent = channel.unary_unary(
                '/transaction_verification.TransactionVerification/RunEvent',
                request_serializer=transaction__verification_dot_transaction__verification__pb2.EventRequest.SerializeToString,
                response_deserializer=transaction__verification_dot_transaction__verification__pb2.EventResponse.FromString,
                _registered_method=True)
        self.ClearOrder = channel.unary_unary(
                '/transaction_verification.TransactionVerification/ClearOrder',
                request_serializer=transaction__verification_dot_transaction__verification__pb2.ClearRequest.SerializeToString,
                response_deserializer=transaction__verification_dot_transaction__verification__pb2.ClearResponse.FromString,
                _registered_method=True)


class TransactionVerificationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CacheOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunEvent(self, request, context):
        """NEW
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransactionVerificationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CacheOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CacheOrder,
                    request_deserializer=transaction__verification_dot_transaction__verification__pb2.CachedOrderRequest.FromString,
                    response_serializer=transaction__verification_dot_transaction__verification__pb2.CacheAck.SerializeToString,
            ),
            'ProcessOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessOrder,
                    request_deserializer=transaction__verification_dot_transaction__verification__pb2.OrderProcessRequest.FromString,
                    response_serializer=transaction__verification_dot_transaction__verification__pb2.TransactionVerificationResponse.SerializeToString,
            ),
            'RunEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.RunEvent,
                    request_deserializer=transaction__verification_dot_transaction__verification__pb2.EventRequest.FromString,
                    response_serializer=transaction__verification_dot_transaction__verification__pb2.EventResponse.SerializeToString,
            ),
            'ClearOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearOrder,
                    request_deserializer=transaction__verification_dot_transaction__verification__pb2.ClearRequest.FromString,
                    response_serializer=transaction__verification_dot_transaction__verification__pb2.ClearResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transaction_verification.TransactionVerification', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('transaction_verification.TransactionVerification', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TransactionVerification(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CacheOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transaction_verification.TransactionVerification/CacheOrder',
            transaction__verification_dot_transaction__verification__pb2.CachedOrderRequest.SerializeToString,
            transaction__verification_dot_transaction__verification__pb2.CacheAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transaction_verification.TransactionVerification/ProcessOrder',
            transaction__verification_dot_transaction__verification__pb2.OrderProcessRequest.SerializeToString,
            transaction__verification_dot_transaction__verification__pb2.TransactionVerificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transaction_verification.TransactionVerification/RunEvent',
            transaction__verification_dot_transaction__verification__pb2.EventRequest.SerializeToString,
            transaction__verification_dot_transaction__verification__pb2.EventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transaction_verification.TransactionVerification/ClearOrder',
            transaction__verification_dot_transaction__verification__pb2.ClearRequest.SerializeToString,
            transaction__verification_dot_transaction__verification__pb2.ClearResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
