syntax = "proto3";
package utils.pb.transaction_verification;

service TransactionVerification {
  rpc CacheOrder(CachedOrderRequest) returns (CacheAck);
  rpc ProcessOrder(OrderProcessRequest) returns (TransactionVerificationResponse);

  // NEW
  rpc RunEvent(EventRequest) returns (EventResponse);
  rpc ClearOrder(ClearRequest) returns (ClearResponse);
}

message CachedOrderRequest {
  string order_id = 1;
  string payload = 2;
  string clock = 3;
}

message OrderProcessRequest {
  string order_id = 1;
}

message TransactionVerificationResponse {
  bool is_valid = 1;
  string message = 2;
}

message CacheAck {
  string message = 1;
}

// NEW
message EventRequest {
  string order_id = 1;
  string event = 2;
  string clock = 3;
}

message EventResponse {
  bool success = 1;
  string message = 2;
  string clock = 3;
}

message ClearRequest {
  string order_id = 1;
  string final_clock = 2;
}

message ClearResponse {
  bool cleared = 1;
  string service = 2;
  string error = 3;
}
