syntax = "proto3";

package transaction_verification;

service TransactionVerification {
  rpc CacheOrder(CachedOrderRequest) returns (CacheAck);
  rpc ProcessOrder(OrderProcessRequest) returns (TransactionVerificationResponse);
}

message CachedOrderRequest {
  string order_id = 1;
  string payload = 2;       // JSON payload
  string clock = 3;         // Serialized vector clock (JSON)
}

message OrderProcessRequest {
  string order_id = 1;
}

message TransactionVerificationResponse {
  bool is_valid = 1;
  string message = 2;
}

message CacheAck {
  string message = 1;
}
