# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from utils.pb.executor import executor_pb2 as utils_dot_pb_dot_executor_dot_executor__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in utils/pb/executor/executor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExecutorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetExecutorID = channel.unary_unary(
                '/pb.executor.Executor/GetExecutorID',
                request_serializer=utils_dot_pb_dot_executor_dot_executor__pb2.Empty.SerializeToString,
                response_deserializer=utils_dot_pb_dot_executor_dot_executor__pb2.ExecutorID.FromString,
                _registered_method=True)
        self.AnnounceLeader = channel.unary_unary(
                '/pb.executor.Executor/AnnounceLeader',
                request_serializer=utils_dot_pb_dot_executor_dot_executor__pb2.ExecutorID.SerializeToString,
                response_deserializer=utils_dot_pb_dot_executor_dot_executor__pb2.Ack.FromString,
                _registered_method=True)
        self.IsAlive = channel.unary_unary(
                '/pb.executor.Executor/IsAlive',
                request_serializer=utils_dot_pb_dot_executor_dot_executor__pb2.Empty.SerializeToString,
                response_deserializer=utils_dot_pb_dot_executor_dot_executor__pb2.Ack.FromString,
                _registered_method=True)


class ExecutorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetExecutorID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnnounceLeader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsAlive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetExecutorID': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExecutorID,
                    request_deserializer=utils_dot_pb_dot_executor_dot_executor__pb2.Empty.FromString,
                    response_serializer=utils_dot_pb_dot_executor_dot_executor__pb2.ExecutorID.SerializeToString,
            ),
            'AnnounceLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.AnnounceLeader,
                    request_deserializer=utils_dot_pb_dot_executor_dot_executor__pb2.ExecutorID.FromString,
                    response_serializer=utils_dot_pb_dot_executor_dot_executor__pb2.Ack.SerializeToString,
            ),
            'IsAlive': grpc.unary_unary_rpc_method_handler(
                    servicer.IsAlive,
                    request_deserializer=utils_dot_pb_dot_executor_dot_executor__pb2.Empty.FromString,
                    response_serializer=utils_dot_pb_dot_executor_dot_executor__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.executor.Executor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pb.executor.Executor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Executor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetExecutorID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.executor.Executor/GetExecutorID',
            utils_dot_pb_dot_executor_dot_executor__pb2.Empty.SerializeToString,
            utils_dot_pb_dot_executor_dot_executor__pb2.ExecutorID.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnnounceLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.executor.Executor/AnnounceLeader',
            utils_dot_pb_dot_executor_dot_executor__pb2.ExecutorID.SerializeToString,
            utils_dot_pb_dot_executor_dot_executor__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsAlive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pb.executor.Executor/IsAlive',
            utils_dot_pb_dot_executor_dot_executor__pb2.Empty.SerializeToString,
            utils_dot_pb_dot_executor_dot_executor__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
