# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: utils/pb/executor/executor.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'utils/pb/executor/executor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n utils/pb/executor/executor.proto\x12\x0bpb.executor\"\x07\n\x05\x45mpty\"\x18\n\nExecutorID\x12\n\n\x02id\x18\x01 \x01(\t\"\'\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xb6\x01\n\x08\x45xecutor\x12<\n\rGetExecutorID\x12\x12.pb.executor.Empty\x1a\x17.pb.executor.ExecutorID\x12;\n\x0e\x41nnounceLeader\x12\x17.pb.executor.ExecutorID\x1a\x10.pb.executor.Ack\x12/\n\x07IsAlive\x12\x12.pb.executor.Empty\x1a\x10.pb.executor.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'utils.pb.executor.executor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=49
  _globals['_EMPTY']._serialized_end=56
  _globals['_EXECUTORID']._serialized_start=58
  _globals['_EXECUTORID']._serialized_end=82
  _globals['_ACK']._serialized_start=84
  _globals['_ACK']._serialized_end=123
  _globals['_EXECUTOR']._serialized_start=126
  _globals['_EXECUTOR']._serialized_end=308
# @@protoc_insertion_point(module_scope)
